export const PROPERTIES_LIST = [
  // 10 Commercial Properties
  {
    id: 1,
    type: "sale",
    name: "Tech Hub Towers",
    country: "Singapore",
    category: "mixed development",
    status: "for sale",
    fullLocation: "Orchard Road, Singapore",
    imagesLinks: ["https://example.com/image1.jpg"],
    propertyType: "commercial",
  },
  {
    id: 2,
    type: "lease",
    name: "Downtown Business Park",
    country: "UK",
    category: "ready to move-in",
    status: "in progress",
    fullLocation: "London, UK",
    imagesLinks: ["https://example.com/image2.jpg"],
    propertyType: "commercial",
  },
  {
    id: 3,
    type: "rent",
    name: "Metro Plaza",
    country: "Australia",
    category: "mixed development",
    status: "in progress",
    fullLocation: "Sydney, Australia",
    imagesLinks: [],
    propertyType: "commercial",
  },
  {
    id: 4,
    type: "sale",
    name: "Harborview Office Tower",
    country: "Hong Kong",
    category: "ultra luxury",
    status: "for sale",
    fullLocation: "Central, Hong Kong",
    imagesLinks: ["https://example.com/image3.jpg"],
    propertyType: "commercial",
  },
  {
    id: 5,
    type: "lease",
    name: "Skyline Business Center",
    country: "USA",
    category: "corporate space",
    status: "for sale",
    fullLocation: "San Francisco, CA, USA",
    imagesLinks: ["https://example.com/image4.jpg"],
    propertyType: "commercial",
  },
  {
    id: 6,
    type: "rent",
    name: "Greenfield Corporate Hub",
    country: "Canada",
    category: "eco-friendly",
    status: "in progress",
    fullLocation: "Toronto, Canada",
    imagesLinks: [],
    propertyType: "commercial",
  },
  {
    id: 7,
    type: "sale",
    name: "Ocean View Commercial Tower",
    country: "UAE",
    category: "luxury",
    status: "for sale",
    fullLocation: "Dubai, UAE",
    imagesLinks: ["https://example.com/image5.jpg"],
    propertyType: "commercial",
  },
  {
    id: 8,
    type: "lease",
    name: "Central Plaza",
    country: "Germany",
    category: "corporate park",
    status: "for sale",
    fullLocation: "Berlin, Germany",
    imagesLinks: [],
    propertyType: "commercial",
  },
  {
    id: 9,
    type: "rent",
    name: "Sunset Bay Office Spaces",
    country: "India",
    category: "luxury",
    status: "in progress",
    fullLocation: "Mumbai, India",
    imagesLinks: ["https://example.com/image6.jpg"],
    propertyType: "commercial",
  },
  {
    id: 10,
    type: "sale",
    name: "Downtown Financial Center",
    country: "Japan",
    category: "financial hub",
    status: "for sale",
    fullLocation: "Tokyo, Japan",
    imagesLinks: [],
    propertyType: "commercial",
  },

  // 10 Residential Properties
  {
    id: 11,
    type: "sale",
    name: "Skyline Residences",
    country: "USA",
    category: "luxury",
    status: "for sale",
    fullLocation: "New York, NY, USA",
    imagesLinks: ["https://example.com/image7.jpg"],
    propertyType: "residential",
  },
  {
    id: 12,
    type: "lease",
    name: "Palm View Villas",
    country: "UAE",
    category: "ultra luxury",
    status: "for rent",
    fullLocation: "Dubai Marina, UAE",
    imagesLinks: [],
    propertyType: "residential",
  },
  {
    id: 13,
    type: "rent",
    name: "Serene Lake Houses",
    country: "Canada",
    category: "landed development",
    status: "in progress",
    fullLocation: "Ontario, Canada",
    imagesLinks: ["https://example.com/image8.jpg"],
    propertyType: "residential",
  },
  {
    id: 14,
    type: "sale",
    name: "Sunset Bay Apartments",
    country: "USA",
    category: "luxury",
    status: "for sale",
    fullLocation: "Los Angeles, CA, USA",
    imagesLinks: [],
    propertyType: "residential",
  },
  {
    id: 15,
    type: "lease",
    name: "Green Fields Estate",
    country: "India",
    category: "landed development",
    status: "for sale",
    fullLocation: "Bangalore, India",
    imagesLinks: ["https://example.com/image9.jpg"],
    propertyType: "residential",
  },
  {
    id: 16,
    type: "rent",
    name: "Coastal Paradise Homes",
    country: "Australia",
    category: "beachfront",
    status: "in progress",
    fullLocation: "Gold Coast, Australia",
    imagesLinks: [],
    propertyType: "residential",
  },
  {
    id: 17,
    type: "sale",
    name: "Hilltop Retreat",
    country: "Germany",
    category: "countryside",
    status: "for sale",
    fullLocation: "Bavaria, Germany",
    imagesLinks: [],
    propertyType: "residential",
  },
  {
    id: 18,
    type: "lease",
    name: "Prestige Garden Homes",
    country: "Singapore",
    category: "eco-living",
    status: "for sale",
    fullLocation: "Sentosa, Singapore",
    imagesLinks: [],
    propertyType: "residential",
  },
  {
    id: 19,
    type: "rent",
    name: "Luxury City Lofts",
    country: "France",
    category: "urban",
    status: "in progress",
    fullLocation: "Paris, France",
    imagesLinks: [],
    propertyType: "residential",
  },
  {
    id: 20,
    type: "sale",
    name: "Mountain View Estates",
    country: "Switzerland",
    category: "private estate",
    status: "for sale",
    fullLocation: "Zermatt, Switzerland",
    imagesLinks: [],
    propertyType: "residential",
  },

  // 10 Industrial Properties
  {
    id: 21,
    type: "sale",
    name: "Prestige Industrial Park",
    country: "Germany",
    category: "ready to move-in",
    status: "for sale",
    fullLocation: "Berlin, Germany",
    imagesLinks: [],
    propertyType: "industrial",
  },
  {
    id: 22,
    type: "lease",
    name: "Mega Warehouse Hub",
    country: "USA",
    category: "logistics",
    status: "for sale",
    fullLocation: "Houston, TX, USA",
    imagesLinks: [],
    propertyType: "industrial",
  },
  {
    id: 23,
    type: "rent",
    name: "Automobile Factory",
    country: "Japan",
    category: "manufacturing",
    status: "in progress",
    fullLocation: "Osaka, Japan",
    imagesLinks: [],
    propertyType: "industrial",
  },
  // (Add 7 more industrial properties following the same pattern)
];

export const MODE = {
  CREATE: "create",
  EDIT: "edit",
};
export const TYPE_OPTION = [
  { label: "Sale", value: "SALE" },
  { label: "Lease", value: "LEASE" },
];
export const CATEGORY_OPTIONS = [
  { label: "Luxury", value: "luxury" },
  { label: "Ultra Luxury", value: "ultra luxury" },
  { label: "Ready to Move-in", value: "ready to move-in" },
  { label: "Landed Development", value: "landed development" },
  { label: "Mixed Development", value: "mixed development" },
];
export const PROPERTY_STATUS = [
  { label: "In Progress", value: "in progress" },
  { label: "For Sale", value: "for sale" },
];
export const PROPERTY_TYPE_OPTIONS = [
  { label: "Residential", value: "RESIDENTIAL" },
  { label: "Commercial", value: "COMMERCIAL" },
  { label: "Industrial", value: "INDUSTRIAL" },
];
export const COUNTRIES = [
  "Hong Kong",
  "India",
  "USA",
  "Germany",
  "Australia",
  "Canada",
  "UK",
  "UAE",
  "Singapore",
];

export const ENQUIRIES_LIST = [
  {
    name: "John Doe",
    email: "johndoe@example.com",
    description: "Looking for a commercial property in downtown.",
    enquiryType: "Property Inquiry",
  },
  {
    name: "Jane Smith",
    email: "janesmith@example.com",
    description: "Interested in renting a residential apartment.",
    enquiryType: "Rental Inquiry",
  },
  {
    name: "Michael Lee",
    email: "michaellee@example.com",
    description: "Need information on industrial properties for lease.",
    enquiryType: "Business Inquiry",
  },
  {
    name: "Emily Johnson",
    email: "emilyjohnson@example.com",
    description: "Seeking a villa in a luxury neighborhood.",
    enquiryType: "Luxury Property Inquiry",
  },
  {
    name: "David Brown",
    email: "davidbrown@example.com",
    description: "Looking to invest in commercial real estate.",
    enquiryType: "Investment Inquiry",
  },
  {
    name: "Sophia Martinez",
    email: "sophiamartinez@example.com",
    description: "Need office space for a startup.",
    enquiryType: "Office Space Inquiry",
  },
  {
    name: "Chris Wilson",
    email: "chriswilson@example.com",
    description: "Interested in purchasing a farmhouse.",
    enquiryType: "Farmhouse Inquiry",
  },
  {
    name: "Olivia Taylor",
    email: "oliviataylor@example.com",
    description: "Looking for co-working space options.",
    enquiryType: "Co-Working Space Inquiry",
  },
  {
    name: "Daniel Harris",
    email: "danielharris@example.com",
    description: "Seeking rental properties in a gated community.",
    enquiryType: "Gated Community Rental",
  },
  {
    name: "Ava Anderson",
    email: "avaanderson@example.com",
    description: "Want to lease an industrial warehouse.",
    enquiryType: "Warehouse Lease Inquiry",
  },
];
